#!/bin/bash
# Remove merged git branches locally and on remote(s)
# Taken from https://gist.github.com/ryanc414/f7686d2c97808b41ed8518a5840e2d78

[ $# -gt 1 ] && echo "Usage: $0 [-n|--dry-run]" && exit 1


git=git
case "$1" in
  "") ;;
  -n | --dry-run) git="echo git" ;;
  *) echo "Unsupported flag: $1"; exit 1
esac


BRANCH_WHITELIST="(\*|master|other-special-branches)"
REMOTES="$(git remote | xargs)"

echo "Deleting merged branches locally"
git branch --merged master \
	| egrep -v "$BRANCH_WHITELIST" \
	| xargs -r $git branch -d

# Delete merged branches from each remote.
for remote in $REMOTES; do
  echo
	echo "Deleting merged branches from $remote"
	$git fetch "$remote" --prune
  [ $? -eq 0 ] && \
	for branch in $(git branch -r --merged master \
										| grep "$remote" \
										| egrep -v "$BRANCH_WHITELIST"); do
		$git push "$remote" --delete "${branch#*/}"
	done
done
